### PR TITLE
Fix `havanna -v`

### PR DESCRIPTION
**Pull request by foca**

### CODE REVIEW

**Comment by foca** [comment]
(Could've solved it by just changing the `-v` handler, but I don't like pulling in the entire gem dependencies during `gem build`)

**Comment by djanowski** [comment]
OTOH, I'm trying to minimize the amount of files my gems require. They get required all the time, while gem build is run every once in a while. Do you think requiring everything on gem build is bad?

**Comment by foca** [comment]
It's not horrible, but it requires that all the dependent gems are installed, which is not something you _should_ need for building the gem. This is more of a purist vs pragmatist thing :)

**Comment by djanowski** [comment]
For now I went with not adding an extra file.

Thanks!

**Pull request closed without merging**
